# Generated by Django 6.0.2 on 2026-03-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('data_catalogacao', models.DateTimeField(auto_now_add=True)),
                ('gratuito', models.BooleanField(default=True)),
                ('prestigio', models.IntegerField(default=0)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='catalogo.tema')),
            ],
        ),
    ]
